name: Send News To Discord

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://ritelsociety-dashboard.vercel.app/api/send-news-safe
